# Generated by Django 4.1 on 2022-09-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='data',
            new_name='raw_data',
        ),
    ]
